# Contextual Chunking — kiểm chứng tính công bằng của khóa Sparse

Phase 1 so sánh **retriever**, nhưng luôn trên **một cách biểu diễn dữ liệu duy nhất**:
mọi chỉ mục đều xây từ `chunk["text"]` và không gì khác. Vậy kết luận *"sparse thắng
dense"* thực chất là *"sparse thắng dense **trên cách biểu diễn này**"*.

Notebook này thay đổi cách biểu diễn rồi đo lại. Toàn bộ nằm trong đây — kỹ thuật dữ liệu,
kỹ thuật đặc trưng, dựng chỉ mục, đánh giá, kiểm định thống kê.

---
## Giả thuyết

Bài báo trung bình cắt thành **2,06 chunk**. Chunk đầu tiên mở đầu bằng chính bài báo
nên tự nó đã có ngữ cảnh. Nhưng các chunk tiếp theo — **51,4% toàn kho** — đến tay
retriever mà **không có dấu hiệu nào cho biết chúng thuộc câu chuyện gì**:

```
chunk 0  "LOS ANGELES (CNN) -- Natalie Cole's search for a new kidney ended..."
chunk 1  "...she said. The transplant was performed Tuesday. Doctors said..."   <- ngữ cảnh?
```

**Can thiệp:** nối đoạn mở đầu bài báo vào trước mỗi chunk tiếp nối.

> ### Một chuyện phải nói trước
> Ý tưởng ban đầu là *"embed thêm metadata/title"*. **Không làm được** — dataset này
> không có metadata thật. `metadata.title` **không phải headline**, nó là **160 ký tự
> đầu của chính bài báo** (đã kiểm: là tiền tố của body ở 200/200 bài đánh giá).
> `url`, `author`, `publish_date` đều là chuỗi rỗng do chunker gán mặc định;
> `publisher` là `"CNN"` cho cả 11.064 bài. Cell 3 sẽ in ra để ông tự thấy.
>
> Thứ duy nhất có giá trị trong trường đó là **đoạn mở đầu bài báo** — nên thí nghiệm
> này là *contextual chunking*, không phải *metadata indexing*. Tên gọi khác nhau,
> và báo cáo phải gọi đúng tên.

> ### Còn trục query prompt thì sao?
> **Đã làm rồi, đúng chuẩn.** `embeddings.py:131-144` áp prefix chính tắc của từng mô hình:
> `query: `/`passage: ` cho e5, và instruction riêng của BGE cho bge-*. bge-m3 đúng ra
> không dùng prefix nào và code cũng không thêm. Nên nhánh dense **chưa bao giờ ngây thơ**
> ở trục đó — thêm prompt tự chế lên trên là đi lệch khỏi phân phối huấn luyện, nhiều
> khả năng làm tệ đi.

---
## Notebook này khác lần chạy Phase 1 ở một điểm quan trọng

Nhánh dense ở đây dùng **tìm kiếm chính xác** (nhân ma trận trên vector đã chuẩn hóa),
**không dùng Chroma/HNSW**. Hai lợi ích:

1. **Tái lập được.** HNSW là chỉ mục *xấp xỉ* và không được truyền seed — chính nguồn
   nhiễu khiến số dense của Phase 1 trôi tới 0,0143 giữa hai lần chạy. Ở đây không có.
2. **Công bằng hơn với dense.** Tìm kiếm chính xác không mất recall do xấp xỉ, nên đây
   là baseline dense **mạnh hơn** so với lần chạy tournament.

Nghĩa là nếu sparse vẫn thắng ở đây, kết luận còn vững hơn trước.

---
## 1. Cấu hình

Bật GPU (T4). Bật Internet. Không cần secret nào (dataset công khai).

Chạy thử trước với `SMOKE = True` (~5 phút) để chắc không lỗi, rồi đổi thành `False`.

In [1]:
SMOKE = False          # True: 40 câu + 3.000 chunk. False: chạy đầy đủ.

REPO_URL    = 'https://github.com/ThomasdeCarpio/Text-Mining---NewsQA-RAG.git'
# Phải là SHA đủ 40 ký tự: 'git fetch' không nhận SHA rút gọn.
REPO_COMMIT = '2735bdc62df371cbdf53e9feff6b9d5cc5524a3f'   # hoặc 'main' để lấy bản mới nhất
HF_REPO_ID  = 'MatchaMacchiato/newsqa_200_11064_v2.0.0'
HF_REVISION = 'b81c8db6847a23272665946c0c43c72e9a212fd9'

# --- Kỹ thuật đặc trưng: nút vặn nằm ở đây ---
CONTEXT_CHARS   = 160     # bao nhiêu ký tự đầu bài báo dùng làm ngữ cảnh
CONTEXT_SEP     = '\n\n' # ngăn cách ngữ cảnh với thân chunk
SKIP_FIRST_CHUNK = True   # chunk 0 đã mở đầu bài báo -> không nối lại (tránh lặp)

DENSE_MODEL  = 'intfloat/e5-base-v2'
SPARSE_MODEL = 'BAAI/bge-m3'
TOP_K        = 10
K_VALUES     = [1, 3, 5, 10]
VARIANTS     = ['resolved', 'original']

BOOTSTRAP_SAMPLES, SEED = 1000, 42

In [2]:
import json, os, subprocess, sys, time
from pathlib import Path

WORK = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path.cwd()
PROJECT = WORK / 'Text-Mining---NewsQA-RAG'
DATA, OUT = WORK / 'ablation_data', WORK / 'ablation_results'
OUT.mkdir(parents=True, exist_ok=True)
os.environ.update({'TOKENIZERS_PARALLELISM':'false','HF_HOME':str(WORK/'hf_cache'),
                   'OMP_NUM_THREADS':'1','PYTHONUNBUFFERED':'1'})

if not PROJECT.exists():
    subprocess.run(['git','clone','--filter=blob:none',REPO_URL,str(PROJECT)],check=True)

def checkout(ref):
    """Lấy đúng ref. Fetch SHA trực tiếp chỉ chạy với SHA đủ 40 ký tự và khi
    server cho phép; nếu không thì fetch cả nhánh rồi checkout."""
    if ref == 'main':
        subprocess.run(['git','fetch','origin','main'],cwd=PROJECT,check=True)
        subprocess.run(['git','checkout','--detach','origin/main'],cwd=PROJECT,check=True)
        return
    if subprocess.run(['git','fetch','--depth=1','origin',ref],cwd=PROJECT).returncode != 0:
        print(f'fetch thẳng {ref[:12]} không được — tải cả lịch sử rồi checkout')
        subprocess.run(['git','fetch','--unshallow','origin'],cwd=PROJECT)
        subprocess.run(['git','fetch','origin'],cwd=PROJECT,check=True)
    subprocess.run(['git','checkout','--detach',ref],cwd=PROJECT,check=True)

checkout(REPO_COMMIT)
print('repo tại', subprocess.run(['git','rev-parse','--short','HEAD'],cwd=PROJECT,
                                 capture_output=True,text=True).stdout.strip())
subprocess.run([sys.executable,'-m','pip','install','-q','-r','requirements-kaggle.txt'],
               cwd=PROJECT,check=True)
sys.path.insert(0, str(PROJECT/'common'))

import numpy as np, pandas as pd, torch
from newsqa_rag.evaluation.metrics import evaluate_retrieval
from newsqa_rag.evaluation.metrics import hit_rate_at_k, mrr_at_k, ndcg_at_k, recall_at_k
from newsqa_rag.experiments import paired_comparison
from newsqa_rag.indexing.learned_sparse_index import BGEM3SparseEncoder, LearnedSparseIndex

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print('device:', DEVICE, '|', torch.cuda.get_device_name(0) if DEVICE=='cuda' else '')

Cloning into '/kaggle/working/Text-Mining---NewsQA-RAG'...
From https://github.com/ThomasdeCarpio/Text-Mining---NewsQA-RAG
 * branch            2735bdc62df371cbdf53e9feff6b9d5cc5524a3f -> FETCH_HEAD
HEAD is now at 2735bdc feat(scripts): package a run's indexes into an uploadable dataset

repo tại 2735bdc
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 76.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.5/250.5 kB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 796.8/796.8 kB 38.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 28.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.1/125.1 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.1/260.1 kB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 59.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 73.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 20.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 102.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 108.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 47.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.7/571.7 kB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 79.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.6/204.6 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.7/94.7 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 947.8/947.8 kB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 114.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 64.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.5/68.5 kB 4.1 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.44.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.44.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.44.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.44.0 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.44.0 which is incompatible.

device: cuda | Tesla T4

---
## 2. Lấy dữ liệu

Tải bundle v2.0.0 đã khóa (kho đã phục hồi phần đuôi bài báo, 22.766 chunk).

In [3]:
if not (DATA/'newsqa_200_11064/final_deduplicated/chunks.jsonl').exists():
    subprocess.run([sys.executable,'scripts/materialize_evaluation_dataset.py',
                    '--repo-id',HF_REPO_ID,'--revision',HF_REVISION,
                    '--output-root',str(DATA/'newsqa_200_11064'),
                    '--db-path',str(DATA/'chroma'),'--skip-vector-index'],
                   cwd=PROJECT,check=True)

ROOT  = DATA/'newsqa_200_11064'
FINAL = ROOT/'final_deduplicated'

def read_jsonl(p):
    return [json.loads(l) for l in Path(p).read_text(encoding='utf-8').splitlines() if l.strip()]

chunks   = read_jsonl(FINAL/'chunks.jsonl')
testsets = {'resolved': read_jsonl(FINAL/'testset_resolved.jsonl'),
            'original': read_jsonl(FINAL/'testset_reviewed_original.jsonl')}
print(f'{len(chunks):,} chunk')
for name, rows in testsets.items():
    print(f'  {name:9s} {len(rows):,} câu hỏi')

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 13.17it/s]

Chunking the 11,064-article corpus and mapping evidence ...
Baseline original testset: /kaggle/working/ablation_data/newsqa_200_11064/final/testset_original.jsonl
Collection: newsqa_val200_s42_7e16e8_309058 (22766 chunks)
Variant manifest: /kaggle/working/ablation_data/newsqa_200_11064/manifests/variant.json
Reviewed original testset: /kaggle/working/ablation_data/newsqa_200_11064/final/testset_reviewed_original.jsonl
Resolved testset: /kaggle/working/ablation_data/newsqa_200_11064/final/testset_resolved.jsonl
Paired clarified testset: /kaggle/working/ablation_data/newsqa_200_11064/final/testset_clarified.jsonl
Excluded questions: /kaggle/working/ablation_data/newsqa_200_11064/final/excluded_questions.jsonl
Review finalization reused the baseline chunks and retrieval indexes.
Deduplicated questions: 1152
Duplicate questions removed: 184
Output: /kaggle/working/ablation_data/newsqa_200_11064/final_deduplicated
Manifest: /kaggle/working/ablation_data/newsqa_200_11064/manifests/deduplicated.variant.json
{
  "dataset_sha256": "282ccdd6a999b623d4d4059ee4c22d1be9b3ac40dac703ea9bf762c7055229c4",
  "dataset_version": "v2.0.0",
  "deduplicated_variant_manifest": "/kaggle/working/ablation_data/newsqa_200_11064/manifests/deduplicated.variant.json",
  "index_fingerprint": "8ceaa1504551876be83de12c3f5277624649ede351e46afc095c9e7b3ff431bb",
  "output_root": "/kaggle/working/ablation_data/newsqa_200_11064",
  "resolved_commit": "b81c8db6847a23272665946c0c43c72e9a212fd9",
  "resumed": false,
  "variant_manifest": "/kaggle/working/ablation_data/newsqa_200_11064/manifests/variant.json"
}
22,766 chunk
  resolved  1,152 câu hỏi
  original  1,152 câu hỏi

---
## 3. Kỹ thuật dữ liệu — trong dataset này thực sự có gì?

Trước khi xây đặc trưng, kiểm tra metadata. Đây là cell chứng minh vì sao
*"embed metadata"* không khả thi.

In [4]:
meta_keys = sorted({k for c in chunks for k in c['metadata']})
print('Các trường metadata và độ đa dạng của chúng:\n')
for k in meta_keys:
    vals = [str(c['metadata'].get(k,'')) for c in chunks]
    nonempty = sum(1 for v in vals if v.strip())
    uniq = len(set(vals))
    verdict = ('RỖNG' if nonempty == 0 else
               'HẰNG SỐ (0 thông tin)' if uniq == 1 else
               f'{uniq:,} giá trị khác nhau')
    print(f'  {k:22s} có giá trị: {nonempty:6,}/{len(chunks):,}   {verdict}')

# title có phải headline không, hay chỉ là phần đầu của body?
is_prefix = sum(1 for c in chunks
                if (t:=str(c['metadata'].get('title','')).strip())
                and c['text'].lstrip().startswith(t))
first_chunks = sum(1 for c in chunks if c['metadata'].get('chunk_index') == 0)
print(f'\ntitle là tiền tố của chính text: {is_prefix:,} chunk '
      f'(và có {first_chunks:,} chunk đầu bài)')
print('\nVí dụ "title":')
for c in chunks[:3]:
    print(f'  {str(c["metadata"]["title"])[:95]!r}')
print('\n=> Đây là 160 ký tự đầu của bài báo, KHÔNG phải headline.')
print('=> Không có metadata nào để index. Nhưng có ngữ cảnh cấp bài báo để tận dụng.')

Các trường metadata và độ đa dạng của chúng:

  article_id             có giá trị: 22,766/22,766   11,064 giá trị khác nhau
  author                 có giá trị:      0/22,766   RỖNG
  canonical_article_id   có giá trị: 22,766/22,766   11,064 giá trị khác nhau
  chunk_index            có giá trị: 22,766/22,766   7 giá trị khác nhau
  corpus_role            có giá trị: 22,766/22,766   2 giá trị khác nhau
  dataset_split          có giá trị: 22,766/22,766   2 giá trị khác nhau
  publish_date           có giá trị:      0/22,766   RỖNG
  publisher              có giá trị: 22,766/22,766   HẰNG SỐ (0 thông tin)
  title                  có giá trị: 22,766/22,766   10,734 giá trị khác nhau
  url                    có giá trị:      0/22,766   RỖNG

title là tiền tố của chính text: 11,064 chunk (và có 11,064 chunk đầu bài)

Ví dụ "title":
  '(CNN) -- The body of Crown Prince Sultan bin Abdulaziz Al-Saud, the heir to the Saudi throne wh'
  '(CNN) -- Only moments after Tiger Woods began reading his apology Friday, writers, pundits and '
  '(CNN) -- Only moments after Tiger Woods began reading his apology Friday, writers, pundits and '

=> Đây là 160 ký tự đầu của bài báo, KHÔNG phải headline.
=> Không có metadata nào để index. Nhưng có ngữ cảnh cấp bài báo để tận dụng.

---
## 4. Kỹ thuật đặc trưng — dựng kho ngữ liệu có ngữ cảnh

**Quy tắc bất di bất dịch:** chỉ đổi `text`. **Không đụng `id`** — nhãn vàng trỏ vào
id, và mọi so sánh phía dưới đều ghép cặp theo id. Đổi id là hỏng toàn bộ thí nghiệm.

In [5]:
def build_contextual(chunks, context_chars=CONTEXT_CHARS, sep=CONTEXT_SEP,
                     skip_first=SKIP_FIRST_CHUNK):
    """Nối ngữ cảnh cấp bài báo vào trước mỗi chunk tiếp nối."""
    out, changed = [], 0
    for c in chunks:
        text = c['text']
        lead = str(c['metadata'].get('title','')).strip()[:context_chars]
        is_first = c['metadata'].get('chunk_index') == 0
        already  = lead and text.lstrip().startswith(lead)
        if lead and not (skip_first and is_first) and not already:
            text = f'{lead}{sep}{text}'
            changed += 1
        out.append({**c, 'text': text})
    return out, changed

contextual, changed = build_contextual(chunks)

assert [a['id'] for a in chunks] == [b['id'] for b in contextual], 'ID phải giữ nguyên'
assert changed > 0, 'không chunk nào được thêm ngữ cảnh — kiểm tra lại CONTEXT_CHARS'
print(f'Đã thêm ngữ cảnh cho {changed:,}/{len(chunks):,} chunk ({changed/len(chunks):.1%})')

ex = next(i for i,(a,b) in enumerate(zip(chunks,contextual)) if a['text'] != b['text'])
print(f'\n--- Ví dụ ({chunks[ex]["id"]}) ---')
print('TRƯỚC:', repr(chunks[ex]['text'][:150]))
print('SAU  :', repr(contextual[ex]['text'][:150]))

Đã thêm ngữ cảnh cho 11,702/22,766 chunk (51.4%)

--- Ví dụ (0025bbc1dd0e_chunk_1) ---
TRƯỚC: 'ESPN.com\'s Bill Simmons called the apology "a borderline train wreck" and said: "It amazes me that Tiger learned little to nothing from the past two m'
SAU  : '(CNN) -- Only moments after Tiger Woods began reading his apology Friday, writers, pundits and tweeters largely split into two camps: those who felt t'

---
## 5. Thu nhỏ mẫu khi chạy thử

Khi `SMOKE`, giữ lại toàn bộ chunk vàng của các câu được chọn rồi mới bù thêm chunk
nhiễu — nếu không, chunk đúng bị loại khỏi kho và mọi chỉ số bằng 0.

In [6]:
if SMOKE:
    for name in VARIANTS:
        testsets[name] = testsets[name][:40]
    gold = {cid for rows in testsets.values() for r in rows
            for cid in (r.get('relevant_chunk_ids') or [])}
    keep, extra = [], 0
    for a, b in zip(chunks, contextual):
        if a['id'] in gold:
            keep.append((a,b))
        elif extra < 3000:
            keep.append((a,b)); extra += 1
    chunks     = [a for a,_ in keep]
    contextual = [b for _,b in keep]
    print(f'SMOKE: {len(chunks):,} chunk ({len(gold)} chunk vàng + {extra:,} nhiễu), '
          f'{len(testsets["resolved"])} câu/biến thể')
else:
    print(f'ĐẦY ĐỦ: {len(chunks):,} chunk, {len(testsets["resolved"]):,} câu/biến thể')

CORPORA = {'plain': chunks, 'contextual': contextual}

ĐẦY ĐỦ: 22,766 chunk, 1,152 câu/biến thể

---
## 6. Nhánh Dense — tìm kiếm chính xác, không dùng HNSW

Mã hóa toàn bộ chunk một lần, giữ trong một ma trận, rồi tính tương đồng bằng phép nhân.
Vector đã chuẩn hóa nên tích vô hướng chính là cosine.

Prefix `passage: ` / `query: ` là **bắt buộc với e5** — đó là cách mô hình được huấn luyện.
Bỏ nó đi là làm hỏng mô hình chứ không phải "thử nghiệm công bằng".

In [7]:
from sentence_transformers import SentenceTransformer

_dense = SentenceTransformer(DENSE_MODEL, device=DEVICE)

def dense_rank(corpus, queries, batch_size=64):
    """Trả về top-K id cho mỗi câu hỏi, bằng tìm kiếm chính xác."""
    ids = [c['id'] for c in corpus]
    docs = _dense.encode([f'passage: {c["text"]}' for c in corpus],
                         batch_size=batch_size, normalize_embeddings=True,
                         convert_to_numpy=True, show_progress_bar=True)
    qs = _dense.encode([f'query: {q}' for q in queries],
                       batch_size=batch_size, normalize_embeddings=True,
                       convert_to_numpy=True)
    sims = qs @ docs.T                       # (n_queries, n_chunks)
    top = np.argsort(-sims, axis=1)[:, :TOP_K]
    return [[ids[j] for j in row] for row in top]

print('dense sẵn sàng — tìm kiếm chính xác, không xấp xỉ, tái lập được')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/67.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/650 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: intfloat/e5-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

dense sẵn sàng — tìm kiếm chính xác, không xấp xỉ, tái lập được

---
## 7. Nhánh Sparse — BGE-M3 learned sparse

Dùng đúng lớp chỉ mục của repo. bge-m3 **không dùng** prefix hướng dẫn nào — đúng chuẩn.

In [8]:
_sparse_encoder = BGEM3SparseEncoder(model_name=SPARSE_MODEL, device=DEVICE)

def sparse_rank(corpus, queries, batch_size=16):
    # encoder truyền qua constructor -> model chỉ nạp một lần cho cả 8 nhánh
    index = LearnedSparseIndex(model_name=SPARSE_MODEL, device=DEVICE,
                               encoder=_sparse_encoder)
    t0 = time.time()
    index.build(corpus, batch_size=batch_size)
    print(f'    dựng chỉ mục sparse trong {time.time()-t0:.0f}s', flush=True)
    return [[hit['id'] for hit in index.query(q, top_k=TOP_K)] for q in queries]

print('sparse sẵn sàng')

sparse sẵn sàng

---
## 8. Chạy toàn bộ 8 nhánh

2 retriever × 2 kho ngữ liệu × 2 biến thể câu hỏi. Đây là phần lâu nhất.

In [9]:
RANKERS = {'dense': dense_rank, 'sparse': sparse_rank}
per_question, aggregate = {}, []

for retriever, rank_fn in RANKERS.items():
    for corpus_name, corpus in CORPORA.items():
        for variant in VARIANTS:
            rows = testsets[variant]
            key = (retriever, corpus_name, variant)
            print(f'\n>>> {retriever} / {corpus_name} / {variant}', flush=True)
            t0 = time.time()
            ranked = rank_fn(corpus, [r['question'] for r in rows])

            samples = [{'question_id': r['question_id'],
                        'relevant_chunk_ids': r.get('relevant_chunk_ids') or [],
                        'retrieved_ids': ids}
                       for r, ids in zip(rows, ranked)]
            per_question[key] = [
                {'question_id': s['question_id'],
                 'retrieval': {f'{fn.__name__.replace("_at_k","")}@{k}':
                               fn(s['relevant_chunk_ids'], s['retrieved_ids'], k)
                               for fn in (hit_rate_at_k, mrr_at_k, ndcg_at_k, recall_at_k)
                               for k in K_VALUES}}
                for s in samples]

            summary = evaluate_retrieval(samples, K_VALUES)
            aggregate.append({'retriever': retriever, 'corpus': corpus_name,
                              'variant': variant, **summary})
            print(f'    nDCG@5={summary["ndcg@5"]:.4f}  Hit@1={summary["hit_rate@1"]:.4f}  '
                  f'Hit@5={summary["hit_rate@5"]:.4f}  ({time.time()-t0:.0f}s)', flush=True)

df = pd.DataFrame(aggregate)
display(df[['retriever','corpus','variant','ndcg@5','mrr@5','hit_rate@1','hit_rate@5']])

>>> dense / plain / resolved

Batches:   0%|          | 0/356 [00:00<?, ?it/s]

    nDCG@5=0.6598  Hit@1=0.5009  Hit@5=0.7908  (712s)

>>> dense / plain / original

Batches:   0%|          | 0/356 [00:00<?, ?it/s]

    nDCG@5=0.2551  Hit@1=0.1693  Hit@5=0.3377  (727s)

>>> dense / contextual / resolved

Batches:   0%|          | 0/356 [00:00<?, ?it/s]

    nDCG@5=0.6891  Hit@1=0.5321  Hit@5=0.8168  (748s)

>>> dense / contextual / original

Batches:   0%|          | 0/356 [00:00<?, ?it/s]

    nDCG@5=0.2965  Hit@1=0.1979  Hit@5=0.3845  (747s)

>>> sparse / plain / resolved

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:01<00:00,  1.61s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 33.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.62s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.67s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.74s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.80s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.74s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.74s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.64s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.60s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.54s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 32.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 55.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 33.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 54.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.18s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 32.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 51.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 25.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 54.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 34.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.80it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 51.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]

    dựng chỉ mục sparse trong 4961s

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1949.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1975.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1809.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2031.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2034.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2108.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1956.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1985.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2144.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2142.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2114.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2242.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1880.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2165.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2235.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2194.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2202.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 51.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1914.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2451.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2166.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2274.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1642.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1675.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2031.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2052.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2423.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 753.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1632.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2090.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1990.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2101.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2046.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2173.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 70.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1995.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2987.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2280.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2241.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2125.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2669.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.23it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2165.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2328.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2170.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1869.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1833.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1906.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2016.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2399.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2008.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2154.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2109.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1850.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1583.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1790.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1952.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 54.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1950.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2164.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1925.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2381.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2041.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2221.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2136.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2593.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1967.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1961.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.40it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2239.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.14it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2076.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2054.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2116.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2603.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2074.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1655.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2183.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 51.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2361.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2326.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2310.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2316.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1829.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2143.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2021.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2298.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2255.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2190.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1940.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.40it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2396.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1985.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1991.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2288.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1931.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2005.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1779.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2359.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2244.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1849.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2240.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2380.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2437.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2060.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2108.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2098.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2028.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2077.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1778.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1883.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1758.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2054.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.36it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1955.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1838.80it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1941.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2174.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2164.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2470.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2407.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1979.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2303.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2399.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2102.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2833.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2172.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2199.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2208.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2308.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2038.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2519.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2169.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2281.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2221.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2402.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2606.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1987.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1757.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2047.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2156.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2135.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2421.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2021.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2181.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2052.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2042.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2158.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2366.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2335.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2038.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2288.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2078.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1686.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2323.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2206.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 53.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2008.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1897.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2206.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2432.89it/s]

    nDCG@5=0.7741  Hit@1=0.6641  Hit@5=0.8681  (5050s)

>>> sparse / plain / original

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 62.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 64.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.73s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 61.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.85s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 56.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.90s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 66.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.82s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 61.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.75s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 59.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 62.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.59s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.54s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 32.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.19s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.20s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 34.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.23s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.54s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 34.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.80it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 33.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 51.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]

    dựng chỉ mục sparse trong 4938s

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1553.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2481.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.72it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2133.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1972.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1718.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1869.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2015.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2557.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2402.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2114.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2079.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1898.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1972.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.34it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2526.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2258.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2277.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1615.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1882.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2164.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1911.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1985.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1867.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2794.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.29it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1802.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1980.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1944.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2501.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1850.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2227.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1976.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2185.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1930.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2045.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3518.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3102.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1973.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2182.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2150.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2194.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2211.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1997.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1745.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1927.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2032.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2529.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1952.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1760.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1976.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1805.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 47.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1822.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1857.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1734.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2316.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2024.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 42.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1703.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2022.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2142.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.14it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2182.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3123.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1790.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2102.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1807.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2223.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1879.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 47.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1971.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 52.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1751.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2109.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2060.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1720.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.06it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2047.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2120.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 38.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2663.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1956.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1866.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2053.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2595.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2279.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2700.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2089.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1902.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2690.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2181.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2280.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1762.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1983.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2003.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2066.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1979.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1999.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2238.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2043.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1781.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1741.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2081.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2234.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2669.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1814.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1901.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2000.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1475.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1837.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2071.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2105.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2223.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1961.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.03it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1960.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.73it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2019.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1913.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2081.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2447.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1951.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2246.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2438.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2166.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2076.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1960.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.88it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2105.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1993.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2888.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.44it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1623.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2414.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1800.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3182.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3366.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1791.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2121.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1934.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1929.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1949.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1808.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.14it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2126.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2162.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1970.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1861.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1653.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2651.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.75it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2106.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2060.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2005.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2121.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2035.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2029.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2145.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2155.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1706.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.92it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1469.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.10it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1658.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2064.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2069.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2184.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1951.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2337.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1965.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2866.92it/s]

    nDCG@5=0.3636  Hit@1=0.2743  Hit@5=0.4462  (5029s)

>>> sparse / contextual / resolved

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 58.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 61.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.75s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 60.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.87s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 54.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.92s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 62.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.84s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 58.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.79s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.72s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 55.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.61s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.34s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.29s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.27s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.23s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.20s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 51.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.56s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.55s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.54s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.48s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.10it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.26it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.80it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 34.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]

    dựng chỉ mục sparse trong 4957s

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1797.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2033.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1971.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2154.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2286.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2495.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2223.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2273.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1982.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2108.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2038.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1881.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2206.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2278.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1889.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1731.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2050.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2021.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1959.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1986.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1920.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2608.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1948.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2048.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2003.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2362.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2206.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2241.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1970.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2033.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2122.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2421.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2228.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2259.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2204.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2542.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.72it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1959.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2275.80it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2163.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2229.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 55.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2309.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2143.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2268.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1992.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2362.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2150.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2577.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2339.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2471.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2028.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2439.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2659.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2074.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2441.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1963.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2894.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3998.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2304.56it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1977.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2222.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2880.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2200.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2205.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2261.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2322.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2295.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1971.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1792.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2075.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1889.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2136.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2097.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1814.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.08it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1638.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 54.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2052.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1793.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1887.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1886.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2240.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1992.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.34it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2351.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1980.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2198.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2078.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.40it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1927.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1920.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1622.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2167.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2170.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2193.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2041.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1914.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2110.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.86it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1985.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2074.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2442.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 516.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 52.35it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2145.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1962.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.47it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2129.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2356.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2281.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2373.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2021.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2334.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2286.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.34it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2366.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2017.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2222.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2351.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2298.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2152.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.26it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2035.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2212.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2328.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1863.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1888.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1848.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1793.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1958.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2109.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2032.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2299.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.49it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1985.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1988.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2008.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1904.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2136.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.14it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2328.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1987.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2234.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.79it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2115.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2128.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2056.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2548.18it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2351.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2369.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.27it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2263.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2268.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.83it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1966.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2128.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.24it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2043.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2008.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2218.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2108.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2130.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.34it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1697.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2068.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.65it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2339.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2289.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2039.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2083.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2170.96it/s]

    nDCG@5=0.7533  Hit@1=0.6198  Hit@5=0.8585  (5048s)

>>> sparse / contextual / original

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 54.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.60s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 61.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.63s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 57.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.77s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 52.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.87s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 62.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.84s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 62.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.85s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 58.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.82s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 57.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.70s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.65s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.59s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.20s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.12it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.18s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.23s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.36it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 32.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 47.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 51.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.30it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.49s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.89it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.51s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 50.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.22it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 49.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.33s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.74it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.50it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.63it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 37.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.97it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 34.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 41.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 48.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 36.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.52s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 39.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.39s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.15it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.45s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.29it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.44s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 40.94it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.43s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 45.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.47s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 46.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.41s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 44.16it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 35.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.46s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 38.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 42.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 43.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:03<00:00,  3.40s/it]

    dựng chỉ mục sparse trong 4956s

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2414.68it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1733.90it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2183.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.57it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2102.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1904.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2027.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2193.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2047.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2300.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.84it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2325.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3120.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2526.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2616.53it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2055.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2019.40it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2368.33it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2229.83it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.81it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2172.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2385.84it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2020.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2194.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2447.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 70.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3199.32it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2345.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2686.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.48it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2101.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2135.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2154.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2258.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.33it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2251.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 70.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2141.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2246.55it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2055.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.42it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2362.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2418.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.98it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2213.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2129.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2156.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2158.67it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2044.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2041.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2898.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.07it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1884.23it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.19it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2484.78it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2084.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2483.31it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2057.04it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2477.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2226.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2177.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.01it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2935.13it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3289.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2336.66it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2090.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.05it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1993.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1972.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2451.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2070.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2258.65it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 66.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2173.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2120.48it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2219.21it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3509.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2371.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2068.20it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2581.11it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 71.31it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3097.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2087.76it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2024.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2060.07it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2290.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2861.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1891.88it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.72it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1872.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.80it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 4275.54it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.95it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2131.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3264.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.50it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2461.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.00it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1965.47it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2218.03it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2211.02it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2267.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.94it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2647.92it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2145.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2226.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.51it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2235.77it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2194.82it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.23it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3446.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1949.93it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2309.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.76it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2257.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 69.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2621.44it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 68.62it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2861.05it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2070.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.46it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2493.64it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2507.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.12it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2425.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2896.62it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.37it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2003.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2031.14it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2373.69it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2209.85it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.39it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2279.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.82it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2017.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.99it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1974.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 56.41it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1849.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 58.71it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.38it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2172.09it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2078.45it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2130.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3266.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2045.00it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.58it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2540.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2174.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.30it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2130.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.85it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2102.41it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2070.24it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2651.27it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.25it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1921.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 51.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1649.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.69it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2108.75it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.72it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1960.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.17it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1989.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.11it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2268.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.22it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2053.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.23it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2118.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.28it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2083.61it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1961.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.61it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2327.58it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.63it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1996.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.97it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2400.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.96it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2451.38it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 51.55it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1679.06it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.18it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2517.59it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.04it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2227.46it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 60.66it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2044.01it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2132.34it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 63.74it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1993.49it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.90it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2310.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.09it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2573.19it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.45it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2323.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.54it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1941.81it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1879.17it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 67.52it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2753.98it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1966.39it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 57.59it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3090.87it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 59.15it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2268.42it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.67it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2253.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.68it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2170.96it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.32it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2418.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 64.20it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2290.72it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 65.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2206.37it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 62.56it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2322.43it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 61.91it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2178.86it/s]

    nDCG@5=0.3494  Hit@1=0.2465  Hit@5=0.4436  (5043s)

  retriever      corpus   variant  ndcg@5   mrr@5  hit_rate@1  hit_rate@5
0     dense       plain  resolved  0.6598  0.6180      0.5009      0.7908
1     dense       plain  original  0.2551  0.2310      0.1693      0.3377
2     dense  contextual  resolved  0.6891  0.6476      0.5321      0.8168
3     dense  contextual  original  0.2965  0.2697      0.1979      0.3845
4    sparse       plain  resolved  0.7741  0.7462      0.6641      0.8681
5    sparse       plain  original  0.3636  0.3389      0.2743      0.4462
6    sparse  contextual  resolved  0.7533  0.7201      0.6198      0.8585
7    sparse  contextual  original  0.3494  0.3213      0.2465      0.4436

---
## 9. Kiểm định theo cặp — contextual có thật sự giúp không?

Mọi nhánh chạy trên **cùng bộ câu hỏi**, nên độ khó của câu hỏi là nhiễu dùng chung và
triệt tiêu khi lấy hiệu theo từng câu. **CI95 của hiệu không chứa 0 ⇒ có ý nghĩa.**

In [10]:
results = []
for retriever in RANKERS:
    for variant in VARIANTS:
        base = per_question[(retriever,'plain',variant)]
        ctx  = per_question[(retriever,'contextual',variant)]
        row = {'retriever': retriever, 'variant': variant}
        for metric in ('retrieval.ndcg@5','retrieval.mrr@5',
                       'retrieval.hit_rate@1','retrieval.hit_rate@5'):
            out = paired_comparison(base, ctx, metric, BOOTSTRAP_SAMPLES, SEED)
            if out:
                sig = out['ci95_low'] > 0 or out['ci95_high'] < 0
                row[metric.replace('retrieval.','')] = (
                    f"{out['mean_delta_right_minus_left']:+.4f} "
                    f"[{out['ci95_low']:+.4f},{out['ci95_high']:+.4f}]"
                    + ('  CO Y NGHIA' if sig else ''))
        results.append(row)

print('Hiệu = contextual trừ plain. Dương = ngữ cảnh giúp ích.\n')
display(pd.DataFrame(results))

Hiệu = contextual trừ plain. Dương = ngữ cảnh giúp ích.

,retriever,variant,ndcg@5,mrr@5,hit_rate@1,hit_rate@5
0,dense,resolved,"+0.0293 [+0.0184,+0.0406] CO Y NGHIA","+0.0296 [+0.0172,+0.0422] CO Y NGHIA","+0.0312 [+0.0122,+0.0503] CO Y NGHIA","+0.0260 [+0.0139,+0.0399] CO Y NGHIA"
1,dense,original,"+0.0414 [+0.0313,+0.0524] CO Y NGHIA","+0.0387 [+0.0282,+0.0505] CO Y NGHIA","+0.0286 [+0.0130,+0.0443] CO Y NGHIA","+0.0469 [+0.0312,+0.0634] CO Y NGHIA"
2,sparse,resolved,"-0.0208 [-0.0288,-0.0136] CO Y NGHIA","-0.0261 [-0.0352,-0.0171] CO Y NGHIA","-0.0443 [-0.0599,-0.0286] CO Y NGHIA","-0.0095 [-0.0183,-0.0009] CO Y NGHIA"
3,sparse,original,"-0.0143 [-0.0220,-0.0068] CO Y NGHIA","-0.0175 [-0.0256,-0.0096] CO Y NGHIA","-0.0278 [-0.0408,-0.0148] CO Y NGHIA","-0.0026 [-0.0139,+0.0078]"

---
## 10. Câu hỏi quyết định: khoảng cách sparse–dense có bị thu hẹp không?

Đây mới là điều thật sự quan trọng. Contextual chunking giúp **cả hai** nhánh — nếu nó
giúp dense nhiều hơn thì khóa sparse cần xem lại; nếu không, khóa được củng cố.

In [11]:
print('Khoảng cách sparse − dense theo nDCG@5 (dương = sparse dẫn trước)\n')
gap_rows = []
for corpus_name in CORPORA:
    for variant in VARIANTS:
        d = paired_comparison(per_question[('dense',corpus_name,variant)],
                              per_question[('sparse',corpus_name,variant)],
                              'retrieval.ndcg@5', BOOTSTRAP_SAMPLES, SEED)
        gap_rows.append({'corpus': corpus_name, 'variant': variant,
                         'gap': round(d['mean_delta_right_minus_left'],4),
                         'ci95': f"[{d['ci95_low']:+.4f},{d['ci95_high']:+.4f}]",
                         'sparse_thang_co_y_nghia': d['ci95_low'] > 0})
gaps = pd.DataFrame(gap_rows)
display(gaps)

print('\n' + '='*70)
for variant in VARIANTS:
    p = gaps[(gaps.corpus=='plain') & (gaps.variant==variant)]['gap'].iloc[0]
    c = gaps[(gaps.corpus=='contextual') & (gaps.variant==variant)]['gap'].iloc[0]
    print(f'{variant:9s}  plain {p:+.4f}  ->  contextual {c:+.4f}   '
          f'(thay đổi {c-p:+.4f})')
print('='*70)
print('\nKhoảng cách THU HẸP đáng kể  -> đáng xem lại khóa, báo cáo phải nêu.')
print('Khoảng cách GIỮ NGUYÊN/RỘNG  -> khóa sparse được củng cố bằng bằng chứng.')

Khoảng cách sparse − dense theo nDCG@5 (dương = sparse dẫn trước)

       corpus   variant     gap               ci95  sparse_thang_co_y_nghia
0       plain  resolved  0.1143  [+0.0939,+0.1346]                     True
1       plain  original  0.1085  [+0.0879,+0.1287]                     True
2  contextual  resolved  0.0641  [+0.0445,+0.0833]                     True
3  contextual  original  0.0529  [+0.0327,+0.0734]                     True

======================================================================
resolved   plain +0.1143  ->  contextual +0.0641   (thay đổi -0.0502)
original   plain +0.1085  ->  contextual +0.0529   (thay đổi -0.0556)
======================================================================

Khoảng cách THU HẸP đáng kể  -> đáng xem lại khóa, báo cáo phải nêu.
Khoảng cách GIỮ NGUYÊN/RỘNG  -> khóa sparse được củng cố bằng bằng chứng.

---
## 11. Lưu kết quả

In [12]:
payload = {
    'smoke': SMOKE,
    'config': {'context_chars': CONTEXT_CHARS, 'skip_first_chunk': SKIP_FIRST_CHUNK,
               'dense_model': DENSE_MODEL, 'sparse_model': SPARSE_MODEL,
               'top_k': TOP_K, 'seed': SEED, 'bootstrap_samples': BOOTSTRAP_SAMPLES,
               'dense_search': 'exact matrix product (no HNSW, reproducible)',
               'n_chunks': len(chunks), 'n_contextualised': changed},
    'aggregate': aggregate,
    'contextual_effect': results,
    'sparse_dense_gap': gap_rows,
}
path = OUT/'contextual_chunking_results.json'
path.write_text(json.dumps(payload, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
print('Đã ghi', path)
print('\nGửi file này lại để cập nhật báo cáo.')
if SMOKE:
    print('\n*** Đây mới là SMOKE. Đặt SMOKE = False rồi chạy lại để lấy số thật. ***')

Đã ghi /kaggle/working/ablation_results/contextual_chunking_results.json

Gửi file này lại để cập nhật báo cáo.